IgorEmelyanovPHSA/immsauto

src/main/java/bcvaxdevit/my/salesforce/com/Pages/SupplyConsolePage.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/BaseTest.java

-added logic to capture log into the console and Test Rail
-small fix for wastage test case, needed to be tested on Jenkins

added logic to capture log into the console and Test Rail

---

src/main/java/bcvaxdevit/my/salesforce/com/Pages/SupplyConsolePage.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Inventory/Adjustments.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Inventory/Wastage.java

-Added adjustment test case
-Minor fix for wastage test case

BCVAX-25828

---

config.properties
pom.xml
src/main/java/bcvaxdevit/my/salesforce/com/Pages/BookAnAppointmentPage.java
src/main/java/bcvaxdevit/my/salesforce/com/Pages/InClinicExperiencePage.java
src/main/java/bcvaxdevit/my/salesforce/com/Pages/LoginPage.java
src/main/java/bcvaxdevit/my/salesforce/com/Pages/RegisterToGetVaccinatedPage.java
src/main/java/bcvaxdevit/my/salesforce/com/Pages/Utils.java
src/test/java/Utilities/ApiQueries.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Portal/Dose1_CitizenBookingAppointment.java

added portal citizen registration testcase

---

config.properties
src/main/java/bcvaxdevit/my/salesforce/com/Pages/BookAnAppointmentPage.java
src/main/java/bcvaxdevit/my/salesforce/com/Pages/LoginPage.java
src/main/java/bcvaxdevit/my/salesforce/com/Pages/TestRailManager.java
src/main/java/bcvaxdevit/my/salesforce/com/Pages/Utils.java
src/test/java/Utilities/ApiQueries.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/BaseTest.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Portal/Dose1_CitizenBookingAppointment.java

Added parameters control config file

refactoringFramework

---

pom.xml
testng.xml

updated testng file

---

src/main/java/bcvaxdevit/my/salesforce/com/Pages/InClinicExperiencePage.java
src/main/java/bcvaxdevit/my/salesforce/com/Pages/SupplyConsolePage.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Inventory/BulkAdjustments.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Inventory/BulkDrafts.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Inventory/BulkTransfers.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Inventory/BulkWastages.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Inventory/Drafts.java

devit test cases updates to add capability to run in different env and minor fixes

devit test cases updates to add capability to run in different env and minor fixes

---

src/main/java/bcvaxdevit/my/salesforce/com/Pages/ClinicInBoxPage.java
src/main/java/bcvaxdevit/my/salesforce/com/Pages/RequisitionPage.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/ClinicInBox/DIWA.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Inventory/RequisitionNotInStock.java
src/test/java/bcvaxdevit/my/salesforce/com/Tests/Inventory/RequisitionSubmit.java

As discussed earlier in meeting, CIB DIWA is updated and have a review guys. it passed on my local couple times.

Updating DIWA in CIB

---

pom.xml
smokeTestsCP.xml
src/main/java/Constansts/Domain.java
src/main/java/Constansts/Header.java
src/main/java/bcvax/pages/CallCenterConsolePage.java
src/main/java/bcvax/pages/CommunityPortalMainPage.java
src/main/java/bcvax/pages/LoginPage.java
src/main/java/bcvax/pages/SupplyConsolePage.java
src/main/java/bcvax/pages/Tables.java
src/test/java/communityPortal/tests/InventoryCP/Transfer.java

- added test case Can_do_Transfer_by_Quantity_within_the_same_Clinic_as_PPHIS_Community
- added step annotation for allure to report on execution steps
- added guava library to simply work with maps, since we still using java 8,

Transfer by dosage and quantatu 

---

smokeTestsCP.xml
src/main/java/bcvax/pages/BasePage.java
src/main/java/bcvax/pages/CommunityPortalMainPage.java
src/main/java/bcvax/pages/SupplyConsolePage.java
src/main/java/bcvax/pages/Tables.java
src/test/java/bcvax/tests/BaseTest.java
src/test/java/communityPortal/tests/InventoryCP/BulkTransfers.java
src/test/java/communityPortal/tests/InventoryCP/Transfer.java

- added test for bulk transfer by quantity to another location
- updated data for transfer in community
Executed on http://phsahrisdev13.phsabc.ehcnet.ca:8080/job/DmytroTest/16/allure/

Bulk transfer by quantity

---

smokeTestsCP.xml
src/main/java/bcvax/pages/BasePage.java
src/main/java/bcvax/pages/CommunityPortalMainPage.java
src/main/java/bcvax/pages/SupplyConsolePage.java
src/main/java/bcvax/pages/Tables.java
src/test/java/bcvax/tests/BaseTest.java
src/test/java/communityPortal/tests/InventoryCP/BulkTransfers.java
src/test/java/communityPortal/tests/InventoryCP/Transfer.java
src/test/java/communityPortal/tests/InventoryCP/TransferCancellation.java

This PR is dependent from https://github.com/IgorEmelyanovPHSA/immsauto/pull/114

Cancel regular transfer

---

config.properties
src/main/java/Constansts/Domain.java
src/main/java/Constansts/Header.java
src/main/java/bcvax/pages/BasePage.java
src/main/java/bcvax/pages/CommunityPortalMainPage.java
src/main/java/bcvax/pages/CommunityPortalMainPage_as_Clinician.java
src/main/java/bcvax/pages/GenericTable.java
src/main/java/bcvax/pages/LoginPage.java
src/main/java/bcvax/pages/RequisitionPage.java
src/main/java/bcvax/pages/SupplyConsolePage.java
src/main/java/bcvax/pages/Tables.java
src/main/java/bcvax/pages/WaitConditions.java
src/test/java/bcvax/tests/BaseTest.java
src/test/java/communityPortal/tests/InventoryCP/BulkDraftsCP.java
src/test/java/communityPortal/tests/InventoryCP/BulkTransfers.java
src/test/java/communityPortal/tests/InventoryCP/BulkTransfersCancellation.java
src/test/java/communityPortal/tests/InventoryCP/DraftsCP.java
src/test/java/communityPortal/tests/InventoryCP/ReceiveSupplies.java
src/test/java/communityPortal/tests/InventoryCP/Transfer.java
src/test/java/communityPortal/tests/InventoryCP/TransferCancellation.java

Update user and fixed current issues
http://phsahrisdev13.phsabc.ehcnet.ca:8080/job/DmytroTest/38/allure/ 
I saw couple case where scenarios occasionally failing 
> Transfer Button getting hidden while popup loads
> Ajax Request expires and vaccine not properly loaded
There is also a need to keep transaction tab clean, noticed when queue getting overloaded some button getting hidden and for some reason scroll not able to identify them

Login as inventory users

---

config.properties
resources/test_data.yml

The single transfers autotest is failing in prodsuppqa_org env. Made the container name unique.

Igor single transfer test refactoring

---

config.properties
resources/test_data.yml
src/main/java/Constansts/Header.java
src/main/java/bcvax/pages/SupplyConsolePage.java
src/main/java/bcvax/pages/Utils.java
src/test/java/bcvax/tests/Inventory/BulkTransfers.java
src/test/java/bcvax/tests/Inventory/Transfer.java

Ran bulk transfer tests against bcvaxdevit_org, prodsuppqa_org, communityqa, communityqa_org.

Igor bulk transfers autotests refactoring

---

config.properties
regressionTestsCP.xml
src/main/java/bcvax/pages/LoginPage.java
src/test/java/communityPortal/tests/Appointment_Scheduling_CP/BookingDose1_COVID19.java
src/test/java/communityPortal/tests/Appointment_Scheduling_CP/BookingDose1_Influenza.java
src/test/java/communityPortal/tests/Appointment_Scheduling_CP/BookingDose2_COVID19.java
src/test/java/communityPortal/tests/DIWA_CP/DIWA_Covid19_CP.java
src/test/java/communityPortal/tests/Historical_Immunisation_CP/Historical_Immunisation_Records_Validation.java
src/test/java/communityPortal/tests/InventoryCP/AdjustmentsCP.java

updates for COMUAT CP: config and TC numbers

updates for COMUAT CP: config and TC numbers

---

src/main/java/bcvax/pages/MainPageCP.java
src/test/java/bcvax/tests/Inventory/ReceiveSupplies.java
src/test/java/communityPortal/tests/DIWA_CP/DIWA_Covid19_CP.java

fixing DIWA with Global search and Valid steps needs to be add for Receiving

fixing DIWA with Global search and Valid steps needs to be add for Receiving 

---

src/main/java/bcvax/pages/SupplyConsolePage.java
src/test/java/bcvax/tests/Inventory/ReceiveSupplies.java

updates for Receive Dosages pickup

updates for Receive Dosages pickup

---

src/test/java/communityPortal/tests/Registration/GoogleSearch_Dojo.java

updates for cross-team meeting

updates for cross-team meeting

---

src/main/java/bcvax/pages/InClinicExperiencePage.java
src/test/java/bcvax/tests/CallCenter/BookingDose1.java
src/test/java/bcvax/tests/CallCenter/BookingDose2.java
src/test/java/bcvax/tests/ClinicInBox/BookingDose1.java
src/test/java/bcvax/tests/InClinicExperience/Dose1_E2E_Covid19.java
src/test/java/bcvax/tests/InClinicExperience/Dose1_E2E_Pneumo.java
src/test/java/bcvax/tests/InClinicExperience/Dose2_E2E_Covid19.java
src/test/java/bcvax/tests/InClinicExperience/UserArrivingWrongClinicRebookAppointment.java
src/test/java/bcvax/tests/Inventory/Consumption.java
src/test/java/communityPortal/tests/VaccineAdministration_CP/E2E_Dose1_Pneumo_CP.java

more scroll for Booking App screen

more scroll for Booking App screen

---

src/test/java/bcvax/tests/InClinicExperience/Dose2_E2E_Covid19.java

devit E2E Vaccine Doce#2 scroll down a bit

devit E2E Vaccine Doce#2 scroll down a bit

---

config.properties
src/test/java/bcvax/tests/InClinicExperience/Dose1_E2E_Covid19.java
src/test/java/bcvax/tests/Inventory/Consumption.java

Consumption Classy fixes COMUAT

Consumption Classy fixes COMUAT

---

src/test/java/bcvax/tests/InClinicExperience/DIWA_ICE.java
src/test/java/bcvax/tests/InClinicExperience/Dose1_E2E_Pneumo.java

COMUAT_Classy updates for Pneumo and DIWA

COMUAT_Classy updates for Pneumo and DIWA

---

config.properties

adding Wrong Clinic user to COMUAT

adding Wrong Clinic user to COMUAT

---

config.properties
src/main/java/bcvax/pages/SupplyConsolePage.java
src/test/java/bcvax/tests/Inventory/TransferCancellation.java

Supply location is not selected from dropdown. Fixed.

Igor administration check in test

---

src/main/java/bcvax/pages/ClinicInBoxPage.java
src/test/java/bcvax/tests/ClinicInBox/DIWA_CIB.java

DIWA lot running against updates

DIWA lot running against updates

---

src/test/java/bcvax/tests/CallCenter/BookingDose1.java
src/test/java/bcvax/tests/CallCenter/BookingDose2.java
src/test/java/bcvax/tests/ClinicInBox/BookingDose1.java
src/test/java/bcvax/tests/InClinicExperience/Dose1_E2E_Covid19.java
src/test/java/bcvax/tests/InClinicExperience/Dose1_E2E_Pneumo.java
src/test/java/bcvax/tests/InClinicExperience/Dose2_E2E_Covid19.java
src/test/java/bcvax/tests/InClinicExperience/UserArrivingWrongClinicRebookAppointment.java

a little scroll down for Booking and VaccineAdmin

a little scroll down for Booking and VaccineAdmin

---

regressionTests.xml
regressionTestsCP.xml
src/test/java/bcvax/tests/InClinicExperience/Check_In_Client_ICE.java
src/test/java/bcvax/tests/InClinicExperience/Dose1_E2E_Covid19.java
src/test/java/bcvax/tests/InClinicExperience/Dose2_E2E_Covid19.java
src/test/java/bcvax/tests/InClinicExperience/VaccineAdministrationCheckIn.java
src/test/java/bcvax/tests/Inventory/Consumption.java
src/test/java/communityPortal/tests/VaccineAdministration_CP/Check_In_Client_CP.java

TC numbers update and renaming Check-In-Citizen

TC numbers update and renaming Check-In-Citizen

---

config.properties

new repointing url for COMUAT(newUI) in configuration.

new repointing url for COMUAT(newUI) in configuration.

---

config.properties

the new SSOTDEV profile configuration adding

the new SSOTDEV profile configuration adding

---

config.properties

API config for the SSOTDEV profile

API config for the SSOTDEV profile

---

pom.xml

Igor defferals autotest

---

config.properties
src/main/java/bcvax/pages/LoginPage.java
src/test/java/bcvax/tests/InClinicExperience/Check_In_Client_ICE.java

adding Clinician ICE Auto user for SSOTDEV

adding Clinician ICE Auto user for SSOTDEV 

---

config.properties

adding org CIB/DIWA/CC users for SSOTDEV env

adding org CIB/DIWA/CC users for SSOTDEV env

---

config.properties
smokeTests.xml
smokeTestsCP.xml

adding SSOTDEV CP profile and smokeTestCP xml

adding SSOTDEV CP profile and smokeTestCP xml

---

src/main/java/bcvax/pages/InClinicExperiencePage.java

SSOTdev DIWA fixes to scroll down a bit to click on SaveConsent button.

SSOTdev DIWA fixes to scroll down a bit to click on SaveConsent button.

---

smokeTests_PrimaryCare_Patient_Org_QAX.xml
src/main/java/primarycare/pages/CommonMethods.java
src/main/java/primarycare/pages/HealthCloudConsolePage.java
src/main/java/primarycare/pages/PortalHealthConnectRegistryPage.java
src/test/java/primarycare/tests/Selenium/Patient_Registry_Portal/Portal_Self_Registration_for_Not_Attached_Patient.java
src/test/java/primarycare/tests/Selenium/Patient_SF_Admin_Interface/AdminInterface_Register_Person_In_Care_Attached_SYSAdmin.java

Adding Validations for Patient and some Timesleeps in QAX

Adding Validations for Patient and some Timesleeps in QAX

---

src/test/java/primarycare/tests/Selenium/Patient_Registry_Portal/Portal_Self_Registration_for_Not_Attached_Patient.java
src/test/java/primarycare/tests/Selenium/Patient_SF_Admin_Interface/AdminInterface_Register_Person_In_Care_Attached_SYSAdmin.java

sleep time and double Refresh before search

sleep time and double Refresh before search

---

src/main/java/primarycare/pages/HealthCloudConsolePage.java
src/test/java/primarycare/tests/Selenium/Patient_SF_Admin_Interface/AdminInterface_Register_Person_In_Care_Attached_SYSAdmin.java

re-write to Yes Attachments and adding Case Validations.

re-write to Yes Attachments and adding Case Validations.

---

src/main/java/primarycare/pages/HealthCloudConsolePage.java
src/test/java/primarycare/tests/Selenium/Patient_Registry_Portal/Portal_Self_Registration_for_Not_Attached_Patient.java
src/test/java/primarycare/tests/Selenium/Patient_SF_Admin_Interface/AdminInterface_Register_Person_In_Care_Attached_SYSAdmin.java

Updates for Attached Primary Registration form QAX

Updates for Attached Primary Registration form QAX
